-- PostgreSQL Database Setup Script
-- Run this script to initialize the contract management database

-- Create database if it doesn't exist
CREATE DATABASE contract_management;

-- Connect to the database
\c contract_management

-- Create tables (these will also be created by schema.sql on app startup)
CREATE TABLE IF NOT EXISTS contracts (
    id UUID PRIMARY KEY,
    title VARCHAR(255),
    description TEXT,
    status VARCHAR(50),
    owner_name VARCHAR(255),
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    contract_name VARCHAR(255),
    original_file_name VARCHAR(255),
    stored_file_name VARCHAR(255),
    content_type VARCHAR(255),
    file_size_bytes BIGINT,
    uploaded_at TIMESTAMP,
    file_path VARCHAR(1024),
    extracted_text TEXT
);

CREATE TABLE IF NOT EXISTS workflow_history (
    id UUID PRIMARY KEY,
    contract_id UUID NOT NULL,
    previous_status VARCHAR(50),
    new_status VARCHAR(50) NOT NULL,
    changed_by VARCHAR(255),
    changed_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_workflow_history_contract
        FOREIGN KEY (contract_id)
        REFERENCES contracts(id)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS contract_chunk (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contract_id UUID NOT NULL,
    chunk_index INTEGER,
    chunk_text TEXT NOT NULL,
    embedding BYTEA NOT NULL,
    CONSTRAINT fk_contract_chunk_contract
        FOREIGN KEY (contract_id)
        REFERENCES contracts(id)
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_contract_status ON contracts(status);
CREATE INDEX IF NOT EXISTS idx_contract_owner_name ON contracts(owner_name);
CREATE INDEX IF NOT EXISTS idx_contract_created_at ON contracts(created_at);
CREATE INDEX IF NOT EXISTS idx_workflow_history_contract_id ON workflow_history(contract_id);
CREATE INDEX IF NOT EXISTS idx_workflow_history_changed_at ON workflow_history(changed_at);
CREATE INDEX IF NOT EXISTS idx_contract_chunk_contract_id ON contract_chunk(contract_id);
