spring:
  application:
    name: contract-management
  config:
    import: optional:classpath:application-secrets.yaml
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/contract_management}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:root}

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  sql:
    init:
      mode: never

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

app:
  upload-dir: uploads

openai:
  api-key: ${OPENAI_API_KEY:}
  model: gpt-4o-mini
  embedding-model: text-embedding-3-small
